config/routes.rb
Rails.application.routes.draw do
  resources :categories
  resources :posts do
    resources :comments 
  end
  devise_scope :user do
    authenticated :user do
      root 'posts#index', as: :authenticated_root
    end
      unauthenticated do
        root 'devise/sessions#new', as: :unauthenticated_root
      end
  end 
  devise_for :users, :controllers =>{registrations: 'registrations'} 
  get 'search',to: "posts#search"
  get 'rails' ,to: "pages#about"
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
    has_many :posts
    validates :category, uniqueness: true 
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :post
  belongs_to :user
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user
  belongs_to :category
  has_many :comments, dependent: :destroy
  has_one_attached :image
  validates :body, presence: true 
  validates :title, presence: true

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    before_action :configure_permitted_parameters, if: :devise_controller?

    protected 

    def configure_permitted_parameters
        devise_parameter_sanitizer.permit(:sign_up, keys: [:role_id, :Name])
    end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :set_category, only: %i[ show edit update destroy ]

  # GET /categories or /categories.json
  def index
    @categories = Category.all
  end

  # GET /categories/1 or /categories/1.json
  def show
  end

  # GET /categories/new
  def new
    @category = Category.new
  end

  # GET /categories/1/edit
  def edit
  end

  # POST /categories or /categories.json
  def create
    @category = Category.new(category_params)
    respond_to do |format|
      if @category.save
        format.html { redirect_to new_post_path}
        format.json { render :show, status: :created, location: @category }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /categories/1 or /categories/1.json
  def update
    respond_to do |format|
      if @category.update(category_params)
        format.html { redirect_to @category, notice: "Category was successfully updated." }
        format.json { render :show, status: :ok, location: @category }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /categories/1 or /categories/1.json
  def destroy
    @category.destroy
    respond_to do |format|
      format.html { redirect_to categories_url, notice: "Category was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_category
      @category = Category.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def category_params
      params.require(:category).permit(:category)
    end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
     def index
         @comment = Comments.all
     end
    def create
        @post = Post.find(params[:post_id])
        @comment = @post.comments.create(comment_params.merge(user_id: current_user.id))
        redirect_to post_path(@post)
    end
    def destroy
        @post = Post.find(params[:post_id])
        @comment = Comment.find(params[:id])
        @comment.destroy
        redirect_to post_path(@post)
    end
    private def comment_params
     params.require(:comment).permit(:body)
    end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end
  def about
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: %i[ show edit update destroy ]
  before_action :authenticate_user!, except: [:show, :index]
  # GET /posts or /posts.json
  def index
    @posts = Post.all
    @categories = Category.all

    cate = params[:cate]
    
    if !cate.nil?
      @posts = Post.where(:category_id => cate)
    else
      @posts = Post.all
    end
    
  end

  def search
    @query = params[:query]
    @posts = Post.where("posts.title ILIKE?",["%#{@query}%"])
  end
  # GET /posts/1 or /posts/1.json
  def show
  end

  # GET /posts/new
  def new
    @post = Post.new
  end

  # GET /posts/1/edit
  def edit
  end

  # PST /posts or /posts.json
  def create
    @post = Post.new(post_params)
     @post.category_id = params[:category_id]
    respond_to do |format|
      if @post.save
        format.html { redirect_to @post, notice: "Post was successfully created." }
        format.json { render :show, status: :created, location: @post }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /posts/1 or /posts/1.json
  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to @post, notice: "Post was successfully updated." }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1 or /posts/1.json
  def destroy
    @post = Post.find(params[:id])
    @post.destroy
    respond_to do |format|
      format.html { redirect_to posts_url, notice: "Post was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def check_user
       if @post.private && current_user != @article.check_user
        redirect_to root_url,alert:"you are not authorized."
       end
      end 
    
    
    
    def set_post
      @post = Post.find(params[:id])
    end
    # Only allow a list of trusted parameters through.
    def post_params
      params.require(:post).permit(:title, :body, :category_id, :image, :private)
    end
end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController
    def sign_up_params
        params.require(:user).permit(:email, :password,:password_confirmation, :name, :Mobile_Number)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/registrations_helper.rb
module RegistrationsHelper
end

app/views/categories/edit.html.erb
<h1>Editing Category</h1>

<%= render 'form', category: @category %>

<%= link_to 'Show', @category %> |
<%= link_to 'Back', categories_path %>

app/views/categories/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Categories</h1>

<table>
  <thead>
    <tr>
      <th>Category</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @categories.each do |category| %>
      <tr>
        <td><%= category.category %></td>
        <td><%= link_to 'Show', category %></td>
        <td><%= link_to 'Edit', edit_category_path(category) %></td>
        <td><%= link_to 'Destroy', category, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Category', new_category_path %>

app/views/categories/new.html.erb
<%= render 'form', category: @category %>

app/views/categories/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Category:</strong>
  <%= @category.category %>
</p>

<%= link_to 'Edit', edit_category_path(@category) %> |
<%= link_to 'Back', categories_path %>

app/views/pages/rails.html.erb
<h1>its rails exam<h1>

app/views/posts/_form.html.erb
<html>
<head>
<meta charset="utf-8" />
<meta
  name="viewport"
  content="width=device-width, initial-scale=1, shrink-to-fit=no"
/>
<meta name="description" content="" />
<meta name="author" content="" />
<title>Clean Blog - Start Bootstrap Theme</title>
<link rel="icon" type="image/x-icon" href="assets/favicon.ico" />
<!-- Font Awesome icons (free version)-->
<script
  src="https://use.fontawesome.com/releases/v5.15.3/js/all.js"
  crossorigin="anonymous"
></script>
<!-- Google fonts-->
<link
  href="https://fonts.googleapis.com/css?family=Lora:400,700,400italic,700italic"
  rel="stylesheet"
  type="text/css"
/>
<link
  href="https://fonts.googleapis.com/css?family=Open+Sans:300italic,400italic,600italic,700italic,800italic,400,300,600,700,800"
  rel="stylesheet"
  type="text/css"
/>
<link rel="stylesheet" href="http://code.ionicframework.com/ionicons/1.5.2/css/ionicons.min.css"/>
<%= stylesheet_link_tag "styles" %>
 <style>

body{
  background-color:#cce6ff;
}
.header{
  margin-left:352px;
  margin-top:30px;
  background-color:#e79e4b;
  width:1200px;
  box-sizing: border-box;
  box-shadow: 0 15px 25px rgba(0, 0, 0, 0.6);
  border-radius: 10px;

}
 

/*H2*/
.create-post{
  margin-top:-20px;
  margin-bottom:20px;
  margin-left:-650px;
  color:#cce6ff;
  text-transform:uppercase;
  font-family: 'Ultra', sans-serif;   
  
}

.new-post {
  margin-top: 100px;
  position: absolute;
  top: 50%;
  left: 50%;
  width: 1200px;
  padding: 40px;
  transform: translate(-50%, -50%);
  background: linear-gradient(#141e30, #243b55);
  box-sizing: border-box;
  box-shadow: 0 15px 25px rgba(0, 0, 0, 0.6);
  border-radius: 10px;
   height:950px;
} 

.image{
  margin-top:10px;
  margin-bottom: 10px;
  color:#fff;
}

.title{
  width: 1125px;
  background: linear-gradient(#141e30, #243b55);
  border: 1px solid #ccc;
  box-shadow: 1px 1px 1px #999;
  border-radius:5px;
  color:#fff ;
  margin-top:10px;
  height:50px;
}

.text-area{
    width: 1125px;
    height: 550px;
    margin-top:10px;  
    align: center;
    line-height: 1.5;
    border-radius: 5px;
    border: 1px solid #ccc;
    box-shadow: 1px 1px 1px #999;
    background: linear-gradient(#141e30, #243b55);
    color:#fff;
}

.image-label{
  color:#fff;
}



.publish-btn{
  position: relative;
  display: inline-block;
  padding: 10px 20px;
  color: #e67e22;
  font-size: 16px;
  text-decoration: none;
  text-transform: uppercase;
  overflow: hidden;
  transition: 0.5s;
  margin-top: 10px;
  letter-spacing: 4px;
  border-radius: 15px;
  background: linear-gradient(#141e30, #243b55);
  

}

.publish-btn:hover{
  color: #eaaa62;
}

.category{
  color:#fff;
  margin-top:10px;
}
.private-label{
  color:#fff;
  margin-top:0px;
}

.new-category{
  background:linear-gradient(#141e30, #243b55);
  margin-left:20px;
  text-decoration:underline;
}

</style> 
</head>
<body>
        <nav class="navbar navbar-expand-lg navbar-light" id="mainNav">
            <div class="container px-4 px-lg-5">

  <div>
  <form class="d-flex"  method="GET" action="/search">
    <input class="form-control me-2" type="search" name="query" placeholder="Search..."/>
    <button class="btn btn-outline_success" type="submit">Search</button>
  </form>
</div>

                <div class="collapse navbar-collapse" id="navbarResponsive">
                    <ul class="navbar-nav ms-auto py-4 py-lg-0">
                        <li class="nav-item">
                         <%= link_to 'Home', posts_path, class:"nav-link px-lg-3 py-3 py-lg-4" %></li>
                        <li class="nav-item">
              <%= link_to 'about',rails_path, class:"nav-link px-lg-3 py-3 py-lg-4" %>
            </li>
            
            <li class="nav-item">
              <%= link_to 'Sign out', destroy_user_session_path, class:"nav-link px-lg-3 py-3 py-lg-4",
                   method: :delete %> 
            </li>
                    </ul>
                </div>
            </div>
        </nav>
<hr class="my-4">

<div class="new-post">
<h1 class="create-post"><center>Inscribe To Describe</center></h1>

<%= form_with(model: post) do |form| %>
  <% if post.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(post.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
        <% post.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
<%=form.label :Category, class:"category" %>
<%= form.select :category_id, Category.all.map {|c| [c.category, c.id]} %>
 <%= link_to "New Category", new_category_url, class:"new-category"%>
</div>
  
  <div class="field">
    <%# <%= form.label :title %>
    <%= form.text_field :title, class:"title", placeholder:"Title" %>
  </div>

 <div class="field">
    <%# <%= form.label :body %> 
    <%= form.text_area :body, class:"text-area", placeholder:"Blog Here..." %>
  </div>


  <div class="field">
    <%= form.label :"Attach Image", class:"image-label" %>
    <%= form.file_field :image, class:"image" %>
  </div>

  


<div>
<%= form.check_box :private %>
<%= form.label :Private, class:"private-label" %>
</div>
  <div class="actions">
    <%= form.submit "Publish", class:"publish-btn" %>
  </div>
<% end %>
</div>


   <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.1/dist/js/bootstrap.bundle.min.js"></script>
    <!-- Core theme JS-->

<script>
/*!
* Start Boot    strap - Clean Blog v6.0.3 (https://startbootstrap.com/theme/clean-blog)
* Copyright 2013-2021 Start Bootstrap
* Licensed under MIT (https://github.com/StartBootstrap/startbootstrap-clean-blog/blob/master/LICENSE)
*/
window.addEventListener('DOMContentLoaded', () => {
    let scrollPos = 0;
    const mainNav = document.getElementById('mainNav');
    const headerHeight = mainNav.clientHeight;
    window.addEventListener('scroll', function() {
        const currentTop = document.body.getBoundingClientRect().top * -1;
        if ( currentTop < scrollPos) {
            // Scrolling Up
            if (currentTop > 0 && mainNav.classList.contains('is-fixed')) {
                mainNav.classList.add('is-visible');
            } else {
                console.log(123);
                mainNav.classList.remove('is-visible', 'is-fixed');
            }
        } else {
            // Scrolling Down
            mainNav.classList.remove(['is-visible']);
            if (currentTop > headerHeight && !mainNav.classList.contains('is-fixed')) {
                mainNav.classList.add('is-fixed');
            }
        }
        scrollPos = currentTop;
    });
})

</script>



</body>
</html>

app/views/posts/index.html.erb
<html>
<head>
<meta charset="utf-8" />
<meta
  name="viewport"
  content="width=device-width, initial-scale=1, shrink-to-fit=no"
/>
<meta name="description" content="" />
<meta name="author" content="" />
<title>Clean Blog - Start Bootstrap Theme</title>
<link rel="icon" type="image/x-icon" href="assets/favicon.ico" />
<!-- Font Awesome icons (free version)-->
<script
  src="https://use.fontawesome.com/releases/v5.15.3/js/all.js"
  crossorigin="anonymous"
></script>
<!-- Google fonts-->
<link
  href="https://fonts.googleapis.com/css?family=Lora:400,700,400italic,700italic"
  rel="stylesheet"
  type="text/css"
/>
<link
  href="https://fonts.googleapis.com/css?family=Open+Sans:300italic,400italic,600italic,700italic,800italic,400,300,600,700,800"
  rel="stylesheet"
  type="text/css"
/>
<link rel="stylesheet" href="http://code.ionicframework.com/ionicons/1.5.2/css/ionicons.min.css"/>


<%= stylesheet_link_tag "styles" %>

</head>
<body>


<%# <% @categories.each  do |category| %>
<%# <%= link_to category.category, posts_path(:cate => category.id) %>



<!---------------------------------->
<!-- Blog Template Complete Code-->
<!---------------------------------->

<nav class="navbar navbar-expand-lg navbar-light" id="mainNav">
      <div class="container px-4 px-lg-5">

<div>
  <form class="d-flex"  method="GET" action="/search">
    <input class="form-control me-2" type="search" name="query" placeholder="Search..."/>
    
    <button class="btn btn-outline_success" type="submit">Search</button>
  </form>
</div>
        <div class="collapse navbar-collapse" id="navbarResponsive">
          <ul class="navbar-nav ms-auto py-4 py-lg-0">
            
            <li class="nav-item">
              <%= link_to 'about',rails_path, class:"nav-link px-lg-3 py-3 py-lg-4" %>
            </li>
            <li class="nav-item">
              <%= link_to 'New Post', new_post_path, class:"nav-link px-lg-3 py-3 py-lg-4" %>
            </li>
            <li class="nav-item">
              <%= link_to 'Sign out', destroy_user_session_path, class:"nav-link px-lg-3 py-3 py-lg-4",
                   method: :delete %> 
          </ul>
        </div>
      </div>
    </nav>
    <!-- Page Header-->
    <header
      class="masthead"
      <%= image_tag('home-bg.jpg',id:'background')%>
    
      <div class="container position-relative px-4 px-lg-5">
        <div class="row gx-4 gx-lg-5 justify-content-center">
          <div class="col-md-10 col-lg-8 col-xl-7">
            <div class="site-heading">
              <h1>Blog Post</h1>
              <span class="subheading">A Blog Theme by Pramath!</span>
            </div>
          </div>
        </div>
      </div>
    </header>
    <!-- Main Content-->  
    <div class="container px-4 px-lg-5">
      <div class="row gx-4 gx-lg-5 justify-content-center">
        <div class="col-md-10 col-lg-8 col-xl-7">
          <!-- Post preview-->
          <!-- Post 1:-->
          <div class="post-preview">
           <% @posts.each do |post| %>
     <% unless post.private && current_user != post.user %> 
     <h2 class="post-title"><%= link_to post.title.titleize , post%></h2>
     <h3 class="post-subtitle"><%= post.body%></h3>
      <h4 class="post-meta">Posted By <%= post.user.name%></h4>
        <% if current_user && current_user.admin %>
        <%= link_to 'Edit', edit_post_path(post) %>
        <%= link_to 'Destroy', post, method: :delete, data: { confirm: 'Are you sure?' } %>
        <% end %>
        <%end%>
      <hr class="my-4" />

    <% end %>
  
          </div>

        </div>
      </div>
    </div>
    <!-- Footer-->
<footer class="border-top">
      <div class="container px-4 px-lg-5">
        <div class="row gx-4 gx-lg-5 justify-content-center">
          <div class="col-md-10 col-lg-8 col-xl-7">
            <ul class="list-inline text-center">
              <li class="list-inline-item">
                <a href="#!">
                  <span class="fa-stack fa-lg">
                    <i class="fas fa-circle fa-stack-2x"></i>
                    <i class="fab fa-twitter fa-stack-1x fa-inverse"></i>
                  </span>
                </a>
              </li>
              <li class="list-inline-item">
                <a href="#!">
                  <span class="fa-stack fa-lg">
                    <i class="fas fa-circle fa-stack-2x"></i>
                    <i class="fab fa-facebook-f fa-stack-1x fa-inverse"></i>
                  </span>
                </a>
              </li>
              <li class="list-inline-item">
                <a href="#https://github.com/Pramath18/finalBlogApp.git">
                  <span class="fa-stack fa-lg">
                    <i class="fas fa-circle fa-stack-2x"></i>
                    <i class="fab fa-github fa-stack-1x fa-inverse"></i>
                  </span>
                </a>
              </li>
            </ul>
            <div class="small text-center text-muted fst-italic">
              Copyright &copy; Pramath's Blog 2021
            </div>
          </div>
        </div>
      </div>
    </footer>
    <!-- Bootstrap core JS -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.1/dist/js/bootstrap.bundle.min.js"></script>
    <!-- Core theme JS-->

<script>
/*!
* Start Boot    strap - Clean Blog v6.0.3 (https://startbootstrap.com/theme/clean-blog)
* Copyright 2013-2021 Start Bootstrap
* Licensed under MIT (https://github.com/StartBootstrap/startbootstrap-clean-blog/blob/master/LICENSE)
*/
window.addEventListener('DOMContentLoaded', () => {
    let scrollPos = 0;
    const mainNav = document.getElementById('mainNav');
    const headerHeight = mainNav.clientHeight;
    window.addEventListener('scroll', function() {
        const currentTop = document.body.getBoundingClientRect().top * -1;
        if ( currentTop < scrollPos) {
            // Scrolling Up
            if (currentTop > 0 && mainNav.classList.contains('is-fixed')) {
                mainNav.classList.add('is-visible');
            } else {
                console.log(123);
                mainNav.classList.remove('is-visible', 'is-fixed');
            }
        } else {
            // Scrolling Down
            mainNav.classList.remove(['is-visible']);
            if (currentTop > headerHeight && !mainNav.classList.contains('is-fixed')) {
                mainNav.classList.add('is-fixed');
            }
        }
        scrollPos = currentTop;
    });
})

</script>
</body>
</html>

app/views/posts/search.html.erb
<html>
<head>
<meta charset="utf-8" />
<meta
  name="viewport"
  content="width=device-width, initial-scale=1, shrink-to-fit=no"
/>
<meta name="description" content="" />
<meta name="author" content="" />
<title>Clean Blog - Start Bootstrap Theme</title>
<link rel="icon" type="image/x-icon" href="assets/favicon.ico" />
<!-- Font Awesome icons (free version)-->
<script
  src="https://use.fontawesome.com/releases/v5.15.3/js/all.js"
  crossorigin="anonymous"
></script>
<!-- Google fonts-->
<link
  href="https://fonts.googleapis.com/css?family=Lora:400,700,400italic,700italic"
  rel="stylesheet"
  type="text/css"
/>
<link
  href="https://fonts.googleapis.com/css?family=Open+Sans:300italic,400italic,600italic,700italic,800italic,400,300,600,700,800"
  rel="stylesheet"
  type="text/css"
/>
<link rel="stylesheet" href="http://code.ionicframework.com/ionicons/1.5.2/css/ionicons.min.css"/>


<%= stylesheet_link_tag "styles" %>

</head>
<body>


<%# <% @categories.each  do |category| %>
<%# <%= link_to category.category, posts_path(:cate => category.id) %>



<!---------------------------------->
<!-- Blog Template Complete Code-->
<!---------------------------------->

<nav class="navbar navbar-expand-lg navbar-light" id="mainNav">
      <div class="container px-4 px-lg-5">

<div>
  <form class="d-flex"  method="GET" action="/search">
    <input class="form-control me-2" type="search" name="query" placeholder="Search..."/>
    
    <button class="btn btn-outline_success" type="submit">Search</button>
  </form>
</div>
        <div class="collapse navbar-collapse" id="navbarResponsive">
          <ul class="navbar-nav ms-auto py-4 py-lg-0">
            <li class="nav-item">
              <%= link_to 'Home',posts_path, class:"nav-link px-lg-3 py-3 py-lg-4" %>
            </li>
            <li class="nav-item">
              <%= link_to 'About',rails_path, class:"nav-link px-lg-3 py-3 py-lg-4" %>
            </li>
            <li class="nav-item">
              <%= link_to 'New Post', new_post_path, class:"nav-link px-lg-3 py-3 py-lg-4" %>
            </li>
            <li class="nav-item">
              <%= link_to 'Sign out', destroy_user_session_path, class:"nav-link px-lg-3 py-3 py-lg-4",
                   method: :delete %> 
            </li>
          </ul>
        </div>
      </div>
    </nav>
    <!-- Page Header-->
    <header
      class="masthead"
      <%= image_tag('home-bg.jpg',id:'background')%>
    
      <div class="container position-relative px-4 px-lg-5">
        <div class="row gx-4 gx-lg-5 justify-content-center">
          <div class="col-md-10 col-lg-8 col-xl-7">
            <div class="site-heading">
              <h1>Search Results</h1>
              <span class="subheading">A Blog Theme by Pramath!</span>
            </div>
          </div>
        </div>
      </div>
    </header>
    <!-- Main Content-->
    <div class="container px-4 px-lg-5">
      <div class="row gx-4 gx-lg-5 justify-content-center">
        <div class="col-md-10 col-lg-8 col-xl-7">
          <!-- Post preview-->
          <!-- Post 1:-->
          <div class="post-preview">
           <% @posts.each do |post| %>
     
     <h2 class="post-title"><%= link_to post.title.titleize , post%></h2>
     <h3 class="post-subtitle"><%= post.body%></h3>
      <h4 class="post-meta">Posted By <%= post.user.name%></h4>
        <% if current_user && current_user.admin %>
        <%= link_to 'Edit', edit_post_path(post) %>
        <%= link_to 'Destroy', post, method: :delete, data: { confirm: 'Are you sure?' } %>
        <% end %>
      <hr class="my-4" />

    <% end %>
  
          </div>

        </div>
      </div>
    </div>
    <!-- Footer-->
    <footer class="border-top">
      <div class="container px-4 px-lg-5">
        <div class="row gx-4 gx-lg-5 justify-content-center">
          <div class="col-md-10 col-lg-8 col-xl-7">
            <ul class="list-inline text-center">
              <li class="list-inline-item">
                <a href="https://github.com/Pramath18/finalBlogApp.git">
                  <span class="fa-stack fa-lg">
                    <i class="fas fa-circle fa-stack-2x"></i>
                    <i class="fab fa-github fa-stack-1x fa-inverse"></i>
                  </span>
                </a>
              </li>
            </ul>
            <div class="small text-center text-muted fst-italic">
              Copyright &copy; Pramath's Blog 2021
            </div>
          </div>
        </div>
      </div>
    </footer>
    <!-- Bootstrap core JS -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.1/dist/js/bootstrap.bundle.min.js"></script>
    <!-- Core theme JS-->

<script>
/*!
* Start Bootstrap - Clean Blog v6.0.3 (https://startbootstrap.com/theme/clean-blog)
* Copyright 2013-2021 Start Bootstrap
* Licensed under MIT (https://github.com/StartBootstrap/startbootstrap-clean-blog/blob/master/LICENSE)
*/
window.addEventListener('DOMContentLoaded', () => {
    let scrollPos = 0;
    const mainNav = document.getElementById('mainNav');
    const headerHeight = mainNav.clientHeight;
    window.addEventListener('scroll', function() {
        const currentTop = document.body.getBoundingClientRect().top * -1;
        if ( currentTop < scrollPos) {
            // Scrolling Up
            if (currentTop > 0 && mainNav.classList.contains('is-fixed')) {
                mainNav.classList.add('is-visible');
            } else {
                console.log(123);
                mainNav.classList.remove('is-visible', 'is-fixed');
            }
        } else {
            // Scrolling Down
            mainNav.classList.remove(['is-visible']);
            if (currentTop > headerHeight && !mainNav.classList.contains('is-fixed')) {
                mainNav.classList.add('is-fixed');
            }
        }
        scrollPos = currentTop;
    });
})

</script>
</body>
</html>